#!/usr/bin/env bash
# A Bash script that stops the 4-to_infinity_and_beyond process
PID=$(pgrep -f 4-to_infinity_and_beyond)
if [ -n "$PID" ]; then
  kill "$PID"
else
  echo "Process not found" > /dev/null
fi
