#!/usr/bin/env bash
# A Bash script that stops the 4-to_infinity_and_beyond process using pkill

PID=$(pgrep -f 4-to_infinity_and_beyond)
if [ -n "$PID" ]; then
  pkill -f 4-to_infinity_and_beyond
  echo "Process $PID terminated"
else
  echo "Process not found"
fi
