#!/usr/bin/env bash
# A Bash script that displays "To infinity and beyond" and handles SIGTERM
trap 'echo "OK"' SIGTERM
while true; do
  echo "To infinity and beyond"
  sleep 2
done


#!/usr/bin/env bash
# A Bash script that stops the 7-highlander process
PID=$(pgrep -f 7-highlander)
if [ -n "$PID" ]; then
  kill "$PID"
else
  echo "Process not found"
fi
