#!/usr/bin/env bash
# Bash script to display "Best School" 10 times with a special case on the 9th iteration

counter=1
while [ $counter -le 10 ]
do
  if [ $counter -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  counter=$((counter + 1))
done
