#!/usr/bin/env bash
# Bash script to display numbers 1 to 20 with special "bad luck" messages using a while loop and case statement

i=1
while [ $i -le 20 ]; do
    echo -n "$i "
    case $i in
        4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
       17) echo "bad luck from Italy";;
        *) echo ;;
    esac
    ((i++))
done
