#!/usr/bin/env bash
FILE="school"

if [ ! -e "$FILE" ]; then
    echo "$FILE doesn't exist"
else
    if [ -d "$FILE" ]; then
        echo "$FILE exists but it's a directory"
    elif [ -f "$FILE" ]; then
        echo "File exist and is a regular file"
        if [ ! -s "$FILE" ]; then
            echo "$FILE exists but empty"
        fi
    fi
fi
